apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: seatunnel-flink-v2-streaming-example
spec:
  image: flink:1.13.6-scala_2.11
  flinkVersion: v1_13
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: job-manager-pod-template
      spec:
        containers:
          - name: flink-main-container
            command: [ "sh","-c","cd /tmp/seatunnel && sh ./bin/install-plugin.sh 2.3.0-beta" ]
            volumeMounts:
              - mountPath: /tmp
                name: tmp
        volumes:
          - name: tmp
            emptyDir: { }
        initContainers:
          - name: artifacts-fetcher
            securityContext:
              privileged: true
            workingDir: /tmp
            image: busybox:latest
            command: [ "sh","-c","wget http://archive.apache.org/dist/incubator/seatunnel/2.3.0-beta/apache-seatunnel-incubating-2.3.0-beta-bin.tar.gz -O /tmp/seatunnel.tar.gz && mkdir /tmp/seatunnel && tar -xzvf /tmp/seatunnel.tar.gz -C /tmp/seatunnel --strip-components 1 && chmod 755 /tmp/seatunnel/bin/install-plugin.sh && echo -e '--connectors-v2-- \n \
              connector-fake \n \
              connector-console \n \
              --end--' > /tmp/seatunnel/config/plugin_config" ]
            volumeMounts:
              - mountPath: /tmp
                name: tmp
          - name: init-plugins
              image: jdk:1.8
              command: [ "sh","-c","cd /tmp/seatunnel && sh ./bin/install-plugin.sh 2.3.0-beta" ]
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///tmp/seatunnel/lib/seatunnel-flink-starter.jar
    entryClass: org.apache.seatunnel.core.starter.flink.SeatunnelFlink
    args: [ "--config", "/tmp/seatunnel/config/flink.streaming.conf.template" ]
    parallelism: 2
    upgradeMode: "stateless"
